# Page settings

#baseURL = http://lisancao.github.io/resume/
languageCode = "en"
title = "LNC"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"


[params]
    author = "CowboySmall"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"


    primaryColor = "#69437a"
    textPrimaryColor = "#292929"



    [params.profile]
        enable = true
        name = "Lisa N. Cao"
        tagline = "BiocTools Head Developer"
        #avatar = "lisancao.jpg"


    [params.contact]
        enable = true
        location = "Vancouver, CA"
        
        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "+1 778 999 4798"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "lisanatashacao@gmail.com"
        #[[params.contact.list]]
        #icon = "fas fa-globe"
        #url = "#lisancao.github.io"
        #text = "lisancao.github.io"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "#lisancao.github.io"
        text = "lisancao.github.io"
        [[params.contact.list]]
        icon = "fab fa-twitter-square"
        url = "#twitter.com/lisancao"
        text = "@lisancao"

    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "R"
        [[params.skills.list.items]]
        details = "Python"
        [[params.skills.list.items]]
        details = "Bash"
        [[params.skills.list.items]]
        details = "System Administration"
        [[params.skills.list]]
        title = "Operating Systems"
        [[params.skills.list.items]]
        details = "Ubuntu/Linux"
        [[params.skills.list.items]]
        details = "Windows 7/8/10+"

        [[params.skills.list]]
        title = "Other Strengths"
        [[params.skills.list.items]]
        details = "Documentation"
        [[params.skills.list.items]]
        details = "Version Control"
        [[params.skills.list.items]]
        details = "Workflow Design"
        [[params.skills.list.items]]
        details = "Communication"
        [[params.skills.list.items]]
        details = "Project Management"
        [[params.skills.list.items]]
        details = "Team Building"


    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Psychology, Bachelor of Arts"
        university = "Simon Fraser University"
        dates = "2012 - Present"

        [[params.education.list]]
        degree = "Dogwood Diploma, IB Certificate"
        university = "Britannia Secondary School"
        dates = "2007 - 2012"

    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "PyLadies Diversity Scholarship"
        body = "Open Source Summit North America"
        date = "2018"
        [[params.awards.list]]
        name = "BC District Award"
        body = "Vancouver School District"
        date = "2012"


    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "English"
        level = "Native"

        [[params.languages.list]]
        name = "Vietnamese"
        level = "Novice"
        
        [[params.languages.list]]
        name = "Khuzdul"
        level = "Enough to get by"


    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Open Source Technology"
        [[params.interests.list]]
        name = "Science Fiction/Futurism"
        [[params.interests.list]]
        name = "News/Social Commentary"
        [[params.interests.list]]
        name = "Attempting Work/Life Balance"



    [params.summary]
        enable = true
        text = "I use R, Bash, and Python to build open source tools for bioinformaticians and behavioural neuroscientists. My most recent and notable achievement includes leading the winning team at Hackseq'19 with my project BiocSwirl, which I continue to develop under the BiocTools name. In the Vancouver area I am recognized for organizing the RLadies chapter and the Vancouver Datajam hackathon. View my CV at: http://bit.do/lnc-cv"


    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "SFU Scientific Programming Group"
        dates = "2018 - Present"
        company = "Workshop Facilitator"
        details = "In collaboration with SFU's Research Commons I lead heavily hands-on workshops covering a variety of R topics for interested graduate students. My workshops and teaching style have recieved positive feedback for being engaging and accessible to all skill levels. I ensure my students leave with a practical and highly usable skill that can be used to immediately improve research. Examples of workshops include:"
        [[params.experience.list.items]]
        details = "Introduction to Bioinformatics with R (90min)"
        [[params.experience.list.items]]
        details = "Heatmaps in R (90min)"
        [[params.experience.list.items]]
        details = "Creating a Resume/CV with Vitae in R (90min)"
        
        [[params.experience.list]]
        title = "Sleep and Circadian Neuroscience Lab"
        dates = "2016 - Present"
        company = "Research Assistant"
        details = "While being introduced last minute onto a Mitacs-funded project in collaboration with BC Hydro, I worked overtime doing data cleaning (tidyverse, purrr, tibble), basic data analyses (base R, psych), linear mixed modelling (lme4), and data visualization on behavioural time-series data in R. My responsibilities on this project included explaining R, consultation, independent research, pivoting code to meet project and deadline requirements, and bringing on colleagues from other departments to collaboratively work to meet tight deadlines. Other duties include:"
        [[params.experience.list.items]]
        details = "***Behavioural Research Methods.*** Conducting behavioural research protocols on rats and mice, performing animal husbandry, basic health checks and time-sensitive circadian feeding protocols"
        [[params.experience.list.items]]
        details = "***Laboratory Skills:*** Cresyl Violet staining, brain sectioning (cryostat and vibratome), animal euthanization (CO2 gas and decapitation), paraformaldehyde perfusions, brain tissue collection & dissection (focus on optic tract/suprachiasmatic nucleus, olfactory bulbs, hippocampus), peripheral tissue collection, intraperitoneal and subcutaneous injections, surgery preparation, solutions preparation, lab housekeeping."
        [[params.experience.list.items]]
        details = "***Certifications:*** CCAC Animal Lab Training (Animals Housed in Vivaria, up to module 12), SFU General Laboratory Safety Training" 
        [[params.experience.list.items]]
        details = "This lab is led by **Dr. Ralph Mistlberger at Simon Fraser University.**" 

        [[params.experience.list]]
        title = "Behavioural Endocrinology Lab"
        dates = "2014 - Present"
        company = "Research Assistant"
        details = "After conducting behavioural protocols on human participants and collecting specimen samples, I became understudy to the lab manager and while performing lab tech duties, I noticed some practices that could have been updated to improve reproducibility and archiving. Currently in the lab I develop a completely reproducible workflow for current and future graduate students in an R package that includes Qualtrics survey porting, variable coding, data preparation, ELISA data analysis, biobehavioural data analysis, and data visualization. Other duties include:"
        [[params.experience.list.items]]
        details = "***Behavioural Research Methods.*** Administering questionnaires, overseeing computer/cognitive tasks and in accordance with university ethics requirements, performing necessary deception with confederates, collecting passive drool from participants, data entry"
        [[params.experience.list.items]]
        details = "***Laboratory Skills:*** Pipette assessment and calibration, running ELISA hormonal immunoassays (Cortisol/Testosterone), restocking supplies, basic lab housekeeping duties, transporting and storing temperature-sensitive samples, conducting literature synthesis for the development of a new hormone protocol, plate reader maintenance"
           [[params.experience.list.items]]
        details = "This lab is led by **Dr. Neil V. Watson at Simon Fraser University.**"

        
        [[params.experience.list]]
        title = "Vancouver Women's Health Collective"
        dates = "2016"
        company = "Co-Investigator"
        details = "My duties were to analyze qualitative data and draw conclusions for the VWHC in terms of the best, most effective role the centre could play in the DTES. This was a role in which I used my past experience working for this organization and my background in research to consult in the direction and methodology of the project. Other duties include:"
        [[params.experience.list.items]]
        details = "***Behavioural Research Methods.*** Sought out participants, scheduled and conducted interviews and follow-ups, transcribed 1-2hr interviews, conducted literature searches and wrote several sections in the paper, provided expertise on: non-profit funding, biopsychosocial correlates of health, low socioeconomic status and health, and women's health issues"
        [[params.experience.list.items]]
        details = " This project was led by **France-Emanuelle Joly with funding from the Canadian Women's Foundation and the Coady Institute.**"
        #[[params.experience.list.items]]
        #details = "*(Not peer reviewed)* Bhandal T, Joly FE, Cao, L. (2016). Women’s health, wellness, and equity in Vancouver and the Downtown Eastside: an environmental scan for decision-makers. (Vancouver, BC: Vancouver Women’s Health Collective)."
  
    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "BiocSwirl"
        meta = "Open Source"
        tagline = "A series of in-depth and easily updateable swirlify made courses used to teach entire bioinformatics workflows in R/Bioconductor using an interactive and easy to digest format. Winner of Hackseq2019."

        [[params.projects.list]]
        title = "BiocTerm"
        meta = "Open Source"
        tagline = "A highly configurable, lightweight and feature rich terminal interface with multi-language support for conducting bioinformatics. BiocTerm currently supports R, Bash, Python, and Vim. Winner of Hackseq2019."

       [[params.projects.list]]
       title = "behavendoR (early stages)"
       meta = "Open Source"
       tagline = "A basic R package used to introduce statistical workflows and reproducibility into the Watson lab and Behavioural Endocrinology field, has basic features and functions that make using R easier for behavioural endocrinologists."
       
     #  [[params.projects.list]]
      # title = "circanalyze (early stages)"
       #meta = "Closed Source"
       #tagline = "A Bioconductor workflow for the analysis of circadian RNA and chIP-seq neuronal cell data." 



    [params.information]
        enable = true
        
        [[params.information.list]]
        title = "Community Involvement"
        [[params.information.list.items]]
        details = "**Vancouver Datajam (Chair, Founder)** · I organize a grassroots data science hackathon that emphasizes accessibility and inclusivity. It is the largest collaboration of the women's coding meetup groups in the area. Our next hack partners with marine life authorities to bridge data and daily life."
        [[params.information.list.items]]
        details = "**RLadies Vancouver (Organizer)** · My job is to cultivate an environment where gender and racial minorities can build R skills starting at any level with a community that is encouraging and nonjudgemental. I organize speakers, workshops, and community building events."
        [[params.information.list.items]]
        details = "**Canadian Association of Neuroscience (Outreach Scientist)** · In 2018 I did some science communication for various public lecture events by writing reading materials and answering public questions and concerns regarding circadian rhythms and sleep." 
        
        [[params.information.list.items]]
        details = "**Vancouver Women's Health Collective (SysAdmin)** · Between 2014-2017 I was a System Administrator for the nonprofit women's centre and oversaw all computer maintenance, networking, and printing for their computer lab running a mix of Windows and Ubuntu systems."

        
        
        [[params.information.list]]
        title = "Invited Talks"
        [[params.information.list.items]]
        details = "2018 · Open Source in (Neuro)Science, PyLadies Talk Night."
        [[params.information.list.items]]
        details = "*References available upon request.*"
          
#        [[params.information.list]]
 #       title = "Current Active Organizations"
  #      details = "Vancouver Datajam (Chair) │ Rladies Vancouver (Organizer) │ SFU Scientific Programming (Workshop Facillitator) │ Pyladies Vancouver (Active Member) │ CAN-ACN (Active Member)"


    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "github.com/lisancao"
        title = "lisancao"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "linkedin.com/in/lisancao"
        title = "lisancao"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "twitter.com/lisancao"
        title = "@lisancao"





